# Generated by Django 4.2.4 on 2023-11-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_book_author_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Model Movie', 'verbose_name_plural': 'Models of type - Movie'},
        ),
    ]
