# Generated by Django 4.2.4 on 2023-10-25 06:35

from django.db import migrations


def set_age_group(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    persons = person_model.objects.all()

    for p_record in persons:
        if p_record.age <= 12:
            p_record.age_group = "Child"
        elif 12 < p_record.age < 18:
            p_record.age_group = "Teen"
        else:
            p_record.age_group = "Adult"

    person_model.objects.bulk_update(persons, ['age_group'])


def set_age_group_default(apps, schema_editor):
    person_model = apps.get_model("main_app", "Person")
    persons = person_model.objects.all()
    age_group_default = person_model._meta.get_field("age_group").default # No age group

    for person in persons:
        person.age_group = age_group_default

    person_model.objects.bulk_update(persons, ['age_group'])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0010_person_alter_course_description'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default)
    ]
