# Generated by Django 4.2.4 on 2023-10-25 11:47

from django.db import migrations


def set_rarity(apps, schema_editor):
    items_model = apps.get_model("main_app", "Item")
    items = items_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif 11 <= item.price <= 20:
            item.rarity = "Very Rare"
        elif 21 <= item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"
    items_model.objects.bulk_update(items, ['rarity'])


def reverse_default_rarity(apps, schema_editor):
    items_model = apps.get_model("main_app", "Item")
    items = items_model.objects.all()
    rarity_default = items_model._meta.get_field("rarity").default  # No age group
    for item in items:
        item.rarity = rarity_default

    items_model.objects.bulk_update(items, ["rarity"])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=reverse_default_rarity)
    ]
