# Generated by Django 4.2.4 on 2023-10-25 12:50

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLIER = 120
    smartphones_model = apps.get_model("main_app", "Smartphone")
    all_phones = smartphones_model.objects.all()

    for phone in all_phones:
        phone.price = len(phone.brand) * MULTIPLIER

    smartphones_model.objects.bulk_update(all_phones, ["price"])


def set_category(apps, schema_editor):
    smartphones_model = apps.get_model("main_app", "Smartphone")
    all_phones = smartphones_model.objects.all()
    for phone in all_phones:
        if phone.price >= 750:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"

    smartphones_model.objects.bulk_update(all_phones, ["category"])


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_price_and_category_default(apps, schema_editor):
    smartphones_model = apps.get_model("main_app", "Smartphone")
    all_phones = smartphones_model.objects.all()
    price_default = smartphones_model._meta.get_field("price").default
    category_default = smartphones_model._meta.get_field("category").default
    for phone in all_phones:
        phone.price = price_default
        phone.category = category_default

    smartphones_model.objects.bulk_update(all_phones, ["price", "category"])


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code=reverse_price_and_category_default)
    ]
